path: C:\Users\cedga\Desktop\Baigiamo_duomenys\merged_dataset
train: images\train
val: images\valid

names:
  0: 'Hardhat'
  1: 'Mask'
  2: 'NO-Hardhat'
  3: 'NO-Mask'
  4: 'NO-Safety Vest'
  5: 'Person'
  6: 'Safety Cone'
  7: 'Safety Vest'
  8: 'Machinery'
  9: 'Vehicle'